# Generated by Django 3.2.5 on 2021-11-11 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='service/')),
                ('detail', models.TextField()),
                ('show', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='team/')),
                ('detail', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('ratings', models.IntegerField()),
                ('role', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('show', models.BooleanField(default=False)),
                ('picture', models.ImageField(upload_to='testimonial/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sols.service')),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/blog')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='PortFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('web', 'Web'), ('data', 'Data'), ('api', 'API'), ('scraping', 'Web Scraping')], max_length=255)),
                ('client_full_name', models.CharField(max_length=255)),
                ('project_date', models.DateTimeField(auto_now_add=True)),
                ('project_url', models.URLField(null=True)),
                ('project_picture', models.ImageField(upload_to='protfolio/')),
                ('project_detail', models.TextField()),
                ('pic2', models.ImageField(null=True, upload_to='portfolio/')),
                ('pic3', models.ImageField(null=True, upload_to='portfolio/')),
                ('pic4', models.ImageField(null=True, upload_to='portfolio/')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sols.service')),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-project_date'],
            },
        ),
    ]
