# Generated by Django 3.2.5 on 2021-11-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sols', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['created'], 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='iden',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='pic4',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
