# Generated by Django 3.2.5 on 2021-11-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sols', '0002_auto_20211111_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='web', max_length=255),
        ),
    ]
