# Generated by Django 3.2.5 on 2021-11-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sols', '0003_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_picture',
            field=models.ImageField(upload_to='portfolio/'),
        ),
    ]
