# Generated by Django 3.2.5 on 2021-11-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sols', '0004_alter_portfolio_project_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tags',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
