# Generated by Django 3.2.5 on 2021-11-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sols', '0005_auto_20211111_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
