# Generated by Django 3.2.5 on 2021-11-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sols', '0006_portfolio_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='service',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='portfolio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sols.portfolio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
