# Generated by Django 3.2.5 on 2021-11-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sols', '0007_auto_20211114_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
