# Generated by Django 3.2.5 on 2021-11-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sols', '0008_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sols.service'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='portfolio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='Sols.portfolio'),
        ),
    ]
